services:
  db:
    container_name: db
    image: chervyakovvladislav/db:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
      - ./volumes/db_logs:/var/lib/postgresql/logs
    command: postgres -c logging_collector=on -c log_directory=/var/lib/postgresql/logs -c log_statement=all
    restart: always
    networks:
      - home-library-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: server
    image: chervyakovvladislav/app:latest
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - home-library-network
    command: sh -c "npm run migration:run:prod && npm run start:prod"
    working_dir: /app

networks:
  home-library-network:
    driver: bridge